// Roman Urdu to Urdu Script Transliterator
// Improved dictionary + phonetic engine with alternative transliterations

const dictionary: Record<string, string> = {
  // Difficult words with multiple transliteration options - these will be handled specially
  // Greetings & Islamic phrases
  "assalam o alaikum": "السلام و علیکم",
  "assalamu alaikum": "السلام علیکم",
  "walaikum assalam": "وعلیکم السلام",
  "bismillah": "بسم اللہ",
  "alhamdulillah": "الحمد للہ",
  "inshallah": "انشاءاللہ",
  "inshaallah": "انشاءاللہ",
  "mashallah": "ماشاءاللہ",
  "subhanallah": "سبحان اللہ",
  "astaghfirullah": "استغفراللہ",
  "jazakallah": "جزاک اللہ",
  "allahu akbar": "اللہ اکبر",

  // Scene headings
  "interior": "اندرونی",
  "exterior": "بیرونی",
  "int": "اند",
  "ext": "بیر",
  "din": "دن",
  "raat": "رات",
  "shaam": "شام",
  "subah": "صبح",
  "subh": "صبح",
  "dopahar": "دوپہر",
  "dopehar": "دوپہر",
  "sham": "شام",

  // Pronouns
  "main": "میں",
  "mujhe": "مجھے",
  "mujhey": "مجھے",
  "mujhko": "مجھکو",
  "mera": "میرا",
  "meri": "میری",
  "mere": "میرے",
  "tu": "تو",
  "tujhe": "تجھے",
  "tera": "تیرا",
  "teri": "تیری",
  "tere": "تیرے",
  "aap": "آپ",
  "apko": "آپکو",
  "aapko": "آپکو",
  "aapka": "آپکا",
  "aapki": "آپکی",
  "aapke": "آپکے",
  "woh": "وہ",
  "wo": "وہ",
  "usse": "اسے",
  "usey": "اسے",
  "usne": "اس نے",
  "uska": "اس کا",
  "uski": "اس کی",
  "uske": "اس کے",
  "hum": "ہم",
  "humein": "ہمیں",
  "humara": "ہمارا",
  "humari": "ہماری",
  "humare": "ہمارے",
  "tum": "تم",
  "tumhein": "تمہیں",
  "tumhara": "تمہارا",
  "tumhari": "تمہاری",
  "tumhare": "تمہارے",
  "woh log": "وہ لوگ",
  "yeh": "یہ",
  "ye": "یہ",
  "yeh log": "یہ لوگ",
  "iss": "اس",
  "kya": "کیا",
  "kaun": "کون\u200f",
  "kahan": "کہاں",
  "kab": "کب",
  "kaise": "کیسے",
  "kyun": "کیوں",
  "kyunke": "کیونکہ",
  "kyunki": "کیونکہ",

  // Common verbs & auxiliaries
  "hai": "ہے",
  "hain": "ہیں",
  "tha": "تھا",
  "thi": "تھی",
  "the": "تھے",
  "hoga": "ہوگا",
  "hogi": "ہوگی",
  "honge": "ہونگے",
  "ho": "ہو",
  "hua": "ہوا",
  "hui": "ہوئی",
  "hue": "ہوئے",
  "kar": "کر",
  "karo": "کرو",
  "karna": "کرنا",
  "kiya": "کیا",
  "kiye": "کیے",
  "na": "نہ",
  "nahi": "نہیں",
  "nahin": "نہیں",
  "nah": "نہ",
  "mat": "مت",
  "bhi": "بھی",
  "hi": "ہی",
  "toh": "تو",
  "aur": "اور",
  "ya": "یا",
  "lekin": "لیکن",
  "magar": "مگر",
  "agar": "اگر",
  "tab": "تب",
  "jab": "جب",
  "ab": "اب",
  "phir": "پھر",
  "phirr": "پھر",
  "jo": "جو",
  "jis": "جس",
  "jab tak": "جب تک",
  "isliye": "اس لیے",
  "warna": "ورنہ",
  "waise": "ویسے",
  "aisa": "ایسا",
  "aisi": "ایسی",
  "aise": "ایسے",
  "jaisa": "جیسا",
  "jaisi": "جیسی",
  "jaise": "جیسے",

  // Postpositions (keep short ones in dictionary to avoid mid-word matching)
  "se": "سے",
  "ko": "کو",
  "ke baad": "کے بعد",
  "ke liye": "کے لیے",
  "ke saath": "کے ساتھ",
  "ke bina": "کے بنا",
  "pehle": "پہلے",
  "baad": "بعد",
  "saath": "ساتھ",
  "bina": "بنا",
  "liye": "لیے",
  "wala": "والا",
  "wali": "والی",
  "walay": "والے",
  "waale": "والے",
  "tak": "تک",
  "par": "پر",
  "pe": "پہ",

  // Common conjunctions / particles (whole-word only via dictionary)
  "ka": "کا",
  "ki": "کی",
  "ke": "کے",
  "ne": "نے",
  "to": "تو",
  "is": "اس",

  // Actions (present)
  "aata": "آتا",
  "aati": "آتی",
  "aate": "آتے",
  "jata": "جاتا",
  "jati": "جاتی",
  "jate": "جاتے",
  "karta": "کرتا",
  "karti": "کرتی",
  "karte": "کرتے",
  "kehta": "کہتا",
  "kehti": "کہتی",
  "kehte": "کہتے",
  "sunta": "سنتا",
  "sunti": "سنتی",
  "sunte": "سنتے",
  "dekhta": "دیکھتا",
  "dekhti": "دیکھتی",
  "dekhte": "دیکھتے",
  "rota": "روتا",
  "roti": "روتی",
  "rote": "روتے",
  "hansa": "ہنسا",
  "hansi": "ہنسی",
  "uthta": "اٹھتا",
  "uthti": "اٹھتی",
  "baithta": "بیٹھتا",
  "baithti": "بیٹھتی",
  "khata": "کھاتا",
  "khati": "کھاتی",
  "peeta": "پیتا",
  "peeti": "پیتی",
  "sota": "سوتا",
  "soti": "سوتی",
  "jaagta": "جاگتا",
  "jaagti": "جاگتی",
  "chahta": "چاہتا",
  "chahti": "چاہتی",
  "chahte": "چاہتے",
  "chahiye": "چاہیے",
  "samjhta": "سمجھتا",
  "samjhti": "سمجھتی",
  "jaanta": "جانتا",
  "jaanti": "جانتی",
  "milta": "ملتا",
  "milti": "ملتی",
  "milte": "ملتے",
  "deta": "دیتا",
  "deti": "دیتی",
  "dete": "دیتے",
  "leta": "لیتا",
  "leti": "لیتی",
  "lete": "لیتے",
  "bolna": "بولنا",
  "bolta": "بولتا",
  "bolti": "بولتی",
  "bolte": "بولتے",
  "rukta": "رکتا",
  "rukti": "رکتی",
  "chodna": "چھوڑنا",
  "chhodna": "چھوڑنا",
  "dhoondna": "ڈھونڈنا",

  // Past tense
  "aaya": "آیا",
  "aayi": "آئی",
  "aaye": "آئے",
  "gaya": "گیا",
  "gayi": "گئی",
  "gaye": "گئے",
  "mila": "ملا",
  "mili": "ملی",
  "mile": "ملے",
  "diya": "دیا",
  "diye": "دیے",
  "liya": "لیا",
  "liye": "لیے",
  "bola": "بولا",
  "boli": "بولی",
  "bole": "بولے",
  "suna": "سنا",
  "suni": "سنی",
  "sune": "سنے",
  "dekha": "دیکھا",
  "dekhi": "دیکھی",
  "dekhe": "دیکھے",
  "samjha": "سمجھا",
  "samjhi": "سمجھی",
  "jaana": "جانا",
  "aana": "آنا",
  "dena": "دینا",
  "lena": "لینا",
  "milna": "ملنا",
  "sunna": "سننا",
  "dekhna": "دیکھنا",
  "rehna": "رہنا",
  "raha": "رہا",
  "rahi": "رہی",
  "rahe": "رہے",
  "rukna": "رکنا",
  "ruka": "رکا",
  "ruki": "رکی",
  "socha": "سوچا",
  "sochna": "سوچنا",
  "bata": "بتا",
  "batao": "بتاؤ",
  "batana": "بتانا",
  "bataaya": "بتایا",
  "samajhna": "سمجھنا",

  // People & relations
  "aadmi": "آدمی",
  "aurat": "عورت",
  "mard": "مرد",
  "larki": "لڑکی",
  "larka": "لڑکا",
  "ladki": "لڑکی",
  "ladka": "لڑکا",
  "bhai": "بھائی",
  "behen": "بہن",
  "baap": "باپ",
  "abbu": "ابو",
  "abu": "ابو",
  "ammi": "امی",
  "maa": "ماں",
  "beta": "بیٹا",
  "beti": "بیٹی",
  "dada": "دادا",
  "dadi": "دادی",
  "nana": "نانا",
  "nani": "نانی",
  "chacha": "چچا",
  "chachi": "چاچی",
  "mama": "ماما",
  "mami": "مامی",
  "khala": "خالہ",
  "phupho": "پھوپھو",
  "dost": "دوست",
  "yaar": "یار",
  "saathi": "ساتھی",
  "dushman": "دشمن",
  "mehman": "مہمان",
  "malik": "مالک",
  "naukar": "نوکر",
  "saab": "صاحب",
  "sahib": "صاحب",
  "janab": "جناب",
  "bibi": "بی بی",
  "begum": "بیگم",

  // Emotions
  "khushi": "خوشی",
  "gham": "غم",
  "gussa": "غصہ",
  "mohabbat": "محبت",
  "pyaar": "پیار",
  "ishq": "عشق",
  "nafrat": "نفرت",
  "darr": "ڈر",
  "khauf": "خوف",
  "umeed": "امید",
  "yaqeen": "یقین",
  "shak": "شک",
  "hairat": "حیرت",
  "taajjub": "تعجب",
  "sharminda": "شرمندہ",
  "pareshan": "پریشان",
  "udaas": "اداس",
  "dard": "درد",
  "sukoon": "سکون",
  "chain": "چین",
  "bechain": "بے چین",
  "tang": "تنگ",
  "thaka": "تھکا",
  "khush": "خوش",

  // Places
  "ghar": "گھر",
  "masjid": "مسجد",
  "school": "اسکول",
  "hospital": "ہسپتال",
  "bazar": "بازار",
  "bazaar": "بازار",
  "shaher": "شہر",
  "shehr": "شہر",
  "gaon": "گاؤں",
  "darya": "دریا",
  "pahaar": "پہاڑ",
  "jungle": "جنگل",
  "sadak": "سڑک",
  "rasta": "راستہ",
  "darwaza": "دروازہ",
  "khirkii": "کھڑکی",
  "kamra": "کمرہ",
  "rasoi": "رسوئی",
  "baithak": "بیٹھک",
  "daftar": "دفتر",
  "qabr": "قبر",
  "qabristaan": "قبرستان",

  // Script terms
  "scene": "منظر",
  "dialogue": "مکالمہ",
  "character": "کردار",
  "kahani": "کہانی",
  "script": "اسکرپٹ",
  "film": "فلم",
  "drama": "ڈرامہ",
  "kirdar": "کردار",
  "mukaalma": "مکالمہ",
  "anjaam": "انجام",
  "ibtida": "ابتدا",
  "waqia": "واقعہ",
  "manzar": "منظر",

  // Time
  "kal": "کل",
  "aaj": "آج",
  "parson": "پرسوں",
  "fajr": "فجر",
  "zuhr": "ظہر",
  "asr": "عصر",
  "maghrib": "مغرب",
  "isha": "عشاء",

  // Numbers
  "ek": "ایک",
  "do": "دو",
  "teen": "تین",
  "chaar": "چار",
  "paanch": "پانچ",
  "chhe": "چھ",
  "saat": "سات",
  "aath": "آٹھ",
  "nau": "نو",
  "das": "دس",
  "bees": "بیس",
  "tees": "تیس",
  "chaalees": "چالیس",
  "pachaas": "پچاس",
  "sau": "سو",
  "hazaar": "ہزار",

  // Adjectives
  "achha": "اچھا",
  "acchi": "اچھی",
  "acche": "اچھے",
  "bura": "برا",
  "buri": "بری",
  "bure": "برے",
  "bada": "بڑا",
  "badi": "بڑی",
  "bade": "بڑے",
  "chota": "چھوٹا",
  "choti": "چھوٹی",
  "lamba": "لمبا",
  "naya": "نیا",
  "nayi": "نئی",
  "naye": "نئے",
  "purana": "پرانا",
  "purani": "پرانی",
  "safed": "سفید",
  "kala": "کالا",
  "kali": "کالی",
  "laal": "لال",
  "hara": "ہرا",
  "neela": "نیلا",
  "peela": "پیلا",
  "sundar": "سندر",
  "khoobsurat": "خوبصورت",
  "bhayanak": "بھیانک",
  "andhera": "اندھیرا",
  "ujala": "اجالا",
  "roshni": "روشنی",
  "awaaz": "آواز",
  "khamoshi": "خاموشی",
  "tez": "تیز",
  "dheeray": "دھیرے",
  "dheere": "دھیرے",
  "jaldi": "جلدی",
  "aaraam": "آرام",
  "mushkil": "مشکل",
  "aasaan": "آسان",

  // Important nouns
  "waqt": "وقت",
  "zamana": "زمانہ",
  "duniya": "دنیا",
  "zindagi": "زندگی",
  "maut": "موت",
  "khwaab": "خواب",
  "sapna": "سپنا",
  "haqeeqat": "حقیقت",
  "jhoot": "جھوٹ",
  "sach": "سچ",
  "insaan": "انسان",
  "banda": "بندہ",
  "dil": "دل",
  "aankh": "آنکھ",
  "haath": "ہاتھ",
  "pair": "پیر",
  "chehra": "چہرہ",
  "sar": "سر",
  "baal": "بال",
  "jism": "جسم",
  "rooh": "روح",
  "khoon": "خون",
  "aansu": "آنسو",
  "muskaan": "مسکان",
  "lafz": "لفظ",
  "baat": "بات",
  "kaam": "کام",
  "paisa": "پیسہ",
  "daulat": "دولت",
  "izzat": "عزت",
  "sharam": "شرم",
  "jurm": "جرم",
  "sazaa": "سزا",
  "insaaf": "انصاف",
  "zulm": "ظلم",
  "jazbah": "جذبہ",
  "jazba": "جذبہ",
  "irada": "ارادہ",
  "himmat": "ہمت",
  "dua": "دعا",
  "eid": "عید",
  "nikah": "نکاح",
  "talaq": "طلاق",
  "jannat": "جنت",
  "jahannum": "جہنم",
  "qismat": "قسمت",
  "taqdeer": "تقدیر",
  "bandagi": "بندگی",
  "ibadat": "عبادت",
  "gunah": "گناہ",
  "toba": "توبہ",
  "darood": "درود",
  "salam": "سلام",
  "pani": "پانی",
  "khana": "کھانا",
  "roti": "روٹی",
  "chai": "چائے",
  "kitaab": "کتاب",
  "kagaz": "کاغذ",
  "qalam": "قلم",
  "safar": "سفر",
  "khabar": "خبر",
  "jawab": "جواب",
  "sawal": "سوال",
  "naam": "نام",
  "khayal": "خیال",
  "fikr": "فکر",
  "koshish": "کوشش",
  "zaroorat": "ضرورت",
  "faida": "فائدہ",
  "nuqsan": "نقصان",
  "taraf": "طرف",
  "jagah": "جگہ",
  "wajah": "وجہ",
  "matlab": "مطلب",
  "maqsad": "مقصد",

  // Geographic names & proper nouns
  "pakistan": "پاکستان",
  "pakistan": "پاکستان",
  "lahore": "لاہور",
  "karachi": "کراچی",
  "islamabad": "اسلام آباد",
  "peshawar": "پشاور",
  "quetta": "کوئٹہ",
  "rawalpindi": "راولپنڈی",
  "multan": "ملتان",
  "faisalabad": "فیصل آباد",
  "sialkot": "سیالکوٹ",
  "hyderabad": "حیدر آباد",
  "sukkur": "سکھر",
  "gilgit": "گلگت",
  "swat": "سوات",
  
  // Difficult words with specific transliterations
  "ayin": "عین",
  "ain": "عین",
  "ghain": "غین",
  "qaaf": "قاف",
  "qaph": "قاف",
  "khaaf": "خاف",
  "hazaa": "ہذا",
  "thaa": "تھا",
  "thay": "تھے",
  "theen": "تھین",
  
  // Additional common words
  "raah": "راہ",
  "saath": "ساتھ",
  "baari": "باری",
  "paas": "پاس",
  "dar": "در",
  "bina": "بنا",
  "sab": "سب",
  "kuch": "کچھ",
  "koi": "کوئی",
  "koyi": "کوئی",
};

// Improved phonetic map — only used for words NOT found in dictionary
// These are applied in sequence on the whole word
// Strategy: map common Urdu phoneme clusters first, then singles
const phoneticRules: [RegExp, string][] = [
  // Aspirated consonants (must come before base letter)
  [/bh/g, "بھ"],
  [/ph/g, "پھ"],
  [/th/g, "تھ"],
  [/dh/g, "دھ"],
  [/jh/g, "جھ"],
  [/kh/g, "کھ"],
  [/gh/g, "گھ"],
  [/ch/g, "چھ"],
  [/rh/g, "ڑھ"],
  [/nh/g, "نھ"],
  [/lh/g, "لھ"],

  // Digraphs
  [/sh/g, "ش"],
  [/zh/g, "ژ"],
  [/ng/g, "نگ"],

  // Long vowels (must come before short)
  [/aa/g, "آ"],
  [/ee/g, "ی"],
  [/ii/g, "ی"],
  [/oo/g, "و"],
  [/uu/g, "و"],
  [/ai/g, "ے"],
  [/ay/g, "ے"],
  [/au/g, "او"],
  [/aw/g, "او"],

  // Consonants
  [/b/g, "ب"],
  [/c/g, "ک"],
  [/d/g, "د"],
  [/f/g, "ف"],
  [/g/g, "گ"],
  [/h/g, "ہ"],
  [/j/g, "ج"],
  [/k/g, "ک"],
  [/l/g, "ل"],
  [/m/g, "م"],
  [/n/g, "ن"],
  [/p/g, "پ"],
  [/q/g, "ق"],
  [/r/g, "ر"],
  [/s/g, "س"],
  [/t/g, "ت"],
  [/v/g, "و"],
  [/w/g, "و"],
  [/x/g, "کس"],
  [/y/g, "ی"],
  [/z/g, "ز"],

  // Short vowels (after consonants)
  [/a/g, "ا"],
  [/e/g, "ے"],
  [/i/g, "ی"],
  [/o/g, "و"],
  [/u/g, "و"],
];

function transliterateUnknownWord(word: string): string {
  const lower = word.toLowerCase();
  let result = lower;
  for (const [pattern, replacement] of phoneticRules) {
    result = result.replace(pattern, replacement);
  }
  return result;
}

export function romanToUrdu(text: string): string {
  if (!text.trim()) return "";

  // Sort dictionary keys by length descending — match longer phrases first
  const sortedKeys = Object.keys(dictionary).sort((a, b) => b.length - a.length);

  // Use a placeholder approach: replace matched dictionary entries with tokens
  // then do phonetic fallback on remaining latin text
  const tokens: string[] = [];
  let processed = text;

  // Replace dictionary matches (whole word / phrase boundary)
  for (const key of sortedKeys) {
    // Escape special regex chars in key
    const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(`(?<![\\u0600-\\u06FF\\w])${escapedKey}(?![\\u0600-\\u06FF\\w])`, "gi");
    processed = processed.replace(regex, (match) => {
      const token = `\x00${tokens.length}\x00`;
      tokens.push(dictionary[key]);
      return token;
    });
  }

  // Phonetic fallback for remaining latin words
  processed = processed.replace(/[a-zA-Z]+/g, (match) => {
    return transliterateUnknownWord(match);
  });

  // Restore dictionary tokens
  processed = processed.replace(/\x00(\d+)\x00/g, (_, idx) => tokens[parseInt(idx)]);

  // Convert punctuation to Urdu equivalents
  processed = processed
    .replace(/\?/g, "؟")
    .replace(/,/g, "،")
    .replace(/\./g, "۔")
    .replace(/;/g, "؛");

  return processed;
}

export function isRomanUrdu(text: string): boolean {
  const latinChars = (text.match(/[a-zA-Z]/g) || []).length;
  const totalChars = text.replace(/\s/g, "").length;
  return totalChars > 0 && latinChars / totalChars > 0.5;
}

// Alternative transliterations for challenging words
export const alternativeTransliterations: Record<string, string[]> = {
  "ayin": ["عین", "آئن", "ایں"],
  "ain": ["عین", "آئن", "ایں"],
  "pakistan": ["پاکستان", "پاکسٹان"],
  "kaaf": ["کاف", "کافِ", "ک"],
  "qaaf": ["قاف", "قافِ", "ق"],
  "hazaaron": ["ہزاروں", "ہزار"],
  "raza": ["رضا", "رaza"],
  "noor": ["نور", "نوور"],
  "hira": ["ہیرا", "ہرا"],
  "saif": ["سیف", "سیف‌"],
  "ayaan": ["ایاں", "آیاں", "ایان"],
  "farah": ["فرح", "فراح"],
  "zain": ["زین", "زین‌", "زائن"],
  "wain": ["وین", "وایں"],
};

// Get alternative transliterations for a word
export function getAlternatives(word: string): string[] {
  const lower = word.toLowerCase();
  if (alternativeTransliterations[lower]) {
    return alternativeTransliterations[lower];
  }
  // Return primary transliteration as first option, then alternatives
  const primary = romanToUrdu(word);
  return [primary];
}
